# NUMPY is a python module which is used for scientific computing .
And the benefits over list are .fast ,less memory,convenient.

In [9]:
import numpy as np
a= np.array([[1,2],[3,4],[5,6]])
a.ndim

2

In [10]:
a.itemsize

4

In [11]:
a.dtype

dtype('int32')

In [12]:
a= np.array([[1,2],[3,4],[5,6]],dtype = np.float64) # we can also change dtype to complex

In [16]:
a.dtype


dtype('float64')

In [17]:
a.itemsize

8

In [18]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [19]:
a.size #Size of an array(No.of elements)

6

In [20]:
a.shape

(3, 2)

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
l= range(5) # it will create an array upto 4
l

range(0, 5)

In [25]:
l[0]


0

In [26]:
l[1]

1

In [27]:
#arange function also does the same
np.arange(1,5)

array([1, 2, 3, 4])

In [28]:
np.arange(1,5,2) #Here step =2

array([1, 3])

In [29]:
#linspace function
np.linspace(1,5,10) # it generates 10 numbers linearly in between those 2 numbers

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [30]:
a.shape

(3, 2)

In [34]:
a.reshape(2,3) # we can reshape to anything but it should support out original array shape

array([[1., 2., 3.],
       [4., 5., 6.]])

In [35]:
a.reshape(6,1)

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [36]:
a.reshape(7,2) # it doesn't support our original shape

ValueError: cannot reshape array of size 6 into shape (7,2)

In [37]:
#rael functions make array flatenate to 1 Dimension.It wont chaneg the original if we want we can store it in one varaiable and get
a.ravel()

array([1., 2., 3., 4., 5., 6.])

In [38]:
a
 

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [40]:
a.min()

1.0

In [41]:
a.max(
)

6.0

In [42]:
a.sum()

21.0

In [43]:
a.sum(axis=0) #will add all elements in colums wise

array([ 9., 12.])

In [44]:
a.sum(axis=1) #will add all elements in row wise

array([ 3.,  7., 11.])

In [46]:
np.sqrt(a) # square root of each function

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [47]:
np.std(a)

1.707825127659933

In [48]:
a1 = np.array([[1,2],[3,4]])
b1= np.array([[5,6],[7,8]])

In [51]:
a1


array([[1, 2],
       [3, 4]])

In [52]:
b1

array([[5, 6],
       [7, 8]])

In [53]:
a1+b1

array([[ 6,  8],
       [10, 12]])

In [54]:
a1*b1

array([[ 5, 12],
       [21, 32]])

In [60]:
a1/b1

array([[1., 1.],
       [1., 1.]])

In [61]:
a1.dot(b1)

array([[ 67,  78],
       [ 91, 106]])

In [64]:
a=np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [65]:
a[1,2] # First row second element

3

In [66]:
a[0:2,2]

array([8, 3])

In [67]:
a[-1]

array([9, 3, 2])

In [68]:
a[-1,0:2]

array([9, 3])

In [69]:
#Include all rows with first and second column only
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [70]:
a=np.array([[6,7,8],[1,2,3],[9,3,2]])
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [71]:
#flat function flattens the array into single dimension
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [72]:
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)

In [73]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [74]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [75]:
#vstack function  vertically stacks the 2 boxes into 1
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [76]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [77]:
a=np.arange(30).reshape(2,15)

In [78]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [79]:
#splitting the array(Vertically slicing) into 3 arrays with equal modules
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [80]:
result = np.hsplit(a,3)
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [81]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [82]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [83]:
#horizontal slicing
result1 = np.vsplit(a,2)

In [84]:
result1[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [85]:
result1[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [86]:
a=np.arange(12).reshape(3,4)

In [87]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
b=a>4 #it compares all elements and checks the condition
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [89]:
a[b] #indexing the array itself.it returns the value from the original array which has True. 

array([ 5,  6,  7,  8,  9, 10, 11])

In [91]:
a[b]=-1 #it changes the value for the condition satisfies.(i.e here a>4)
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [95]:
#nditer good way for iteration.it allows us to do iteration in variety of ways.use documentation of "nditer" to know more.
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
for x in np.nditer(a,order = 'C'): #row wise flatteing
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [98]:
for x in np.nditer(a,order = 'F'): #column wise flattening
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [100]:
for x in np.nditer(a,order = 'F',flags = ['external_loop']): #here we want the columns at a time to print not the element in columns
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [101]:
#modifying the array.by using 'readwrite'
for x in np.nditer(a,op_flags=['readwrite']):
    x[...] = x*x #modifyng to squares of each number in an array.

In [103]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [105]:
#Iterating 2 arrays: we can iterate if shapes of 2 arrays are comapatible 
b=np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [107]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
